### ISSUE TITLE
Model is not found

### ISSUE THREAD

**Issue by tomotana14** [Robert0812/deepsaldet#1]
I can't get model files.
www.ee.cuhk.edu.hk/~rzhao/sharedata/model_imagenet_bbox_pretrain_iter_780000_cascade_stage2_iter_80000.caffemodel
www.ee.cuhk.edu.hk/~rzhao/sharedata/model_imagenet_padimage_pretrain_iter_600000_stage1_iter_80000.caffemodel

thanks.

**Comment by Robert0812** [comment]
Problem fixed. Models are now shared via Dropbox.

**Comment by tomotana14** [comment]
Thank you for the quick response!

**Comment by pranjal23** [comment]
Dropbox has temporarily disabled the account as it is generating too much traffic
