### ISSUE TITLE
Exception TypeError: TypeError("'NoneType' object is not callable",)

### ISSUE THREAD

**Issue by zhdsmy** [Robert0812/deepsaldet#2]
Loading images ...
Superpixel segmentation ...
Extracting windows from 0-th image ... [Total: 10]
Extracting windows from 1-th image ... [Total: 10]
Extracting windows from 2-th image ... [Total: 10]
Extracting windows from 3-th image ... [Total: 10]
Extracting windows from 4-th image ... [Total: 10]
Extracting windows from 5-th image ... [Total: 10]
Extracting windows from 6-th image ... [Total: 10]
Extracting windows from 7-th image ... [Total: 10]
Extracting windows from 8-th image ... [Total: 10]
Extracting windows from 9-th image ... [Total: 10]
1023
E0702 16:22:40.293716  7705 extract_features.cpp:49] Using GPU
E0702 16:22:40.293944  7705 extract_features.cpp:55] Using Device_id=0
E0702 16:22:42.401402  7705 extract_features.cpp:135] Extacting features for 1024 images ...
E0702 16:22:45.945432  7705 extract_features.cpp:173] Extracted features of 1000 query images for feature blob fc8_msra10k
E0702 16:22:46.005468  7705 extract_features.cpp:185] Extracted features of 1024 query images for feature blob fc8_msra10k
E0702 16:22:46.005511  7705 extract_features.cpp:189] Successfully extracted the features!
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method UmfpackContext.new_del of <scipy.sparse.linalg.dsolve.umfpack.umfpack.UmfpackContext object at 0x7f9c0aa0aa50>> ignored

The saliency images are generated, but with this error information. Is it OK?

**Comment by Robert0812** [comment]
Does this error happen after stage 1 prediction? Are saliency images with suffix _mc generated?

**Comment by zhdsmy** [comment]
@Robert0812 Thanks for you reply. I found no problem when I updated the scipy to the newest version.
